USE DATABASE TRAVEL_DW;
USE SCHEMA GOLD;

CREATE OR REPLACE PROCEDURE SP_LOAD_FACT_BOOKING()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN

    INSERT INTO FACT_BOOKING
    (
        BOOKING_ID,
        CUSTOMER_KEY,
        HOTEL_KEY,
        DATE_KEY,
        PAYMENT_ID,
        TOTAL_AMOUNT,
        BOOKING_STATUS,
        STAY_DAYS
    )

    SELECT

        B.BOOKING_ID,

        C.CUSTOMER_KEY,

        H.HOTEL_KEY,

        TO_NUMBER(TO_CHAR(B.CHECK_IN_DATE,'YYYYMMDD')),

        P.PAYMENT_ID,

        B.TOTAL_AMOUNT,

        B.BOOKING_STATUS,

        DATEDIFF(
            DAY,
            B.CHECK_IN_DATE,
            B.CHECK_OUT_DATE
        )

    FROM SILVER.BOOKING_SILVER B

    INNER JOIN DIM_CUSTOMER C
        ON B.CUSTOMER_ID = C.CUSTOMER_ID
       AND C.IS_CURRENT = TRUE

    INNER JOIN DIM_HOTEL H
        ON B.HOTEL_ID = H.HOTEL_ID

    LEFT JOIN SILVER.PAYMENT_SILVER P
        ON B.BOOKING_ID = P.BOOKING_ID;

    RETURN 'FACT_BOOKING loaded successfully';

END;
$$;