MERGE INTO BOOKING_SILVER T

USING BOOKING_BRONZE S

ON T.BOOKING_ID = S.BOOKING_ID

WHEN MATCHED THEN
UPDATE SET

    T.CUSTOMER_ID      = S.CUSTOMER_ID,
    T.HOTEL_ID         = S.HOTEL_ID,
    T.CHECK_IN_DATE    = S.CHECK_IN_DATE,
    T.CHECK_OUT_DATE   = S.CHECK_OUT_DATE,
    T.TOTAL_AMOUNT     = S.TOTAL_AMOUNT,
    T.BOOKING_STATUS   = S.BOOKING_STATUS,
    T.UPDATED_DATE     = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN

INSERT
(
BOOKING_ID,
CUSTOMER_ID,
HOTEL_ID,
CHECK_IN_DATE,
CHECK_OUT_DATE,
TOTAL_AMOUNT,
BOOKING_STATUS,
CREATED_DATE,
UPDATED_DATE
)

VALUES
(
S.BOOKING_ID,
S.CUSTOMER_ID,
S.HOTEL_ID,
S.CHECK_IN_DATE,
S.CHECK_OUT_DATE,
S.TOTAL_AMOUNT,
S.BOOKING_STATUS,
CURRENT_TIMESTAMP(),
CURRENT_TIMESTAMP()
);