USE DATABASE ENTERPRISE_DW;

USE SCHEMA LANDING;

CREATE TABLE IF NOT EXISTS CUSTOMER_LANDING
(
    CUSTOMER_ID VARCHAR,

    FIRST_NAME VARCHAR,

    LAST_NAME VARCHAR,

    EMAIL VARCHAR,

    PHONE VARCHAR,

    COUNTRY VARCHAR,

    CREATED_DATE TIMESTAMP,

    UPDATED_DATE TIMESTAMP,

    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),

    SOURCE_SYSTEM VARCHAR
);

CREATE TABLE IF NOT EXISTS HOTEL_LANDING
(
    HOTEL_ID VARCHAR,

    HOTEL_NAME VARCHAR,

    CITY VARCHAR,

    COUNTRY VARCHAR,

    STAR_RATING NUMBER,

    CREATED_DATE TIMESTAMP,

    UPDATED_DATE TIMESTAMP,

    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),

    SOURCE_SYSTEM VARCHAR
);

CREATE TABLE IF NOT EXISTS BOOKING_LANDING
(
    BOOKING_ID VARCHAR,

    CUSTOMER_ID VARCHAR,

    HOTEL_ID VARCHAR,

    CHECKIN_DATE DATE,

    CHECKOUT_DATE DATE,

    TOTAL_AMOUNT NUMBER(18,2),

    BOOKING_STATUS VARCHAR,

    CREATED_DATE TIMESTAMP,

    UPDATED_DATE TIMESTAMP,

    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),

    SOURCE_SYSTEM VARCHAR
);

CREATE TABLE IF NOT EXISTS PAYMENT_LANDING
(
    PAYMENT_ID VARCHAR,

    BOOKING_ID VARCHAR,

    PAYMENT_MODE VARCHAR,

    PAYMENT_STATUS VARCHAR,

    PAYMENT_AMOUNT NUMBER(18,2),

    PAYMENT_DATE TIMESTAMP,

    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),

    SOURCE_SYSTEM VARCHAR
);

CREATE TABLE IF NOT EXISTS REVIEW_LANDING
(
    REVIEW_ID VARCHAR,

    BOOKING_ID VARCHAR,

    CUSTOMER_ID VARCHAR,

    HOTEL_ID VARCHAR,

    REVIEW_SCORE NUMBER,

    REVIEW_TEXT VARCHAR,

    REVIEW_DATE TIMESTAMP,

    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),

    SOURCE_SYSTEM VARCHAR
); 