COPY INTO CUSTOMER_LANDING
FROM @LANDING_STAGE/customers.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = CONTINUE;

COPY INTO HOTEL_LANDING
FROM @LANDING_STAGE/hotels.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = CONTINUE;

COPY INTO BOOKING_LANDING
FROM @LANDING_STAGE/bookings.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = CONTINUE;

COPY INTO PAYMENT_LANDING
FROM @LANDING_STAGE/payments.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = CONTINUE;

COPY INTO REVIEW_LANDING
FROM @LANDING_STAGE/reviews.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = CONTINUE;