CREATE WAREHOUSE ETL_WH
WITH
WAREHOUSE_SIZE='MEDIUM'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE
INITIALLY_SUSPENDED=TRUE
COMMENT='Warehouse for ELT Processing';

CREATE WAREHOUSE REPORTING_WH
WITH
WAREHOUSE_SIZE='MEDIUM'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE
INITIALLY_SUSPENDED=TRUE
COMMENT='Warehouse for Report Processing';

CREATE WAREHOUSE ADMIN_WH
WITH
WAREHOUSE_SIZE='MEDIUM'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE
INITIALLY_SUSPENDED=TRUE
COMMENT='Warehouse for Admin Processing';