CREATE TABLE CUSTOMER_BRONZE
(
    CUSTOMER_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    COUNTRY STRING,

    CREATED_DATE DATE,
    UPDATED_DATE DATE,
    SOURCE_SYSTEM STRING,

    LOAD_TIMESTAMP TIMESTAMP,
    BATCH_ID STRING,
    RECORD_STATUS STRING
);

CREATE TABLE HOTEL_BRONZE
(
    CUSTOMER_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    COUNTRY STRING,

    CREATED_DATE DATE,
    UPDATED_DATE DATE,
    SOURCE_SYSTEM STRING,

    LOAD_TIMESTAMP TIMESTAMP,
    BATCH_ID STRING,
    RECORD_STATUS STRING
);

CREATE TABLE BOOKING_BRONZE
(
    CUSTOMER_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    COUNTRY STRING,

    CREATED_DATE DATE,
    UPDATED_DATE DATE,
    SOURCE_SYSTEM STRING,

    LOAD_TIMESTAMP TIMESTAMP,
    BATCH_ID STRING,
    RECORD_STATUS STRING
);

CREATE TABLE PAYMENT_BRONZE
(
    CUSTOMER_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    COUNTRY STRING,

    CREATED_DATE DATE,
    UPDATED_DATE DATE,
    SOURCE_SYSTEM STRING,

    LOAD_TIMESTAMP TIMESTAMP,
    BATCH_ID STRING,
    RECORD_STATUS STRING
);

CREATE TABLE REVIEW_BRONZE
(
    CUSTOMER_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    COUNTRY STRING,

    CREATED_DATE DATE,
    UPDATED_DATE DATE,
    SOURCE_SYSTEM STRING,

    LOAD_TIMESTAMP TIMESTAMP,
    BATCH_ID STRING,
    RECORD_STATUS STRING
);