USE DATABASE TRAVEL_DW;
USE SCHEMA GOLD;

INSERT INTO FACT_BOOKING
(
    BOOKING_ID,
    CUSTOMER_KEY,
    HOTEL_KEY,
    DATE_KEY,
    PAYMENT_ID,
    TOTAL_AMOUNT,
    BOOKING_STATUS,
    STAY_DAYS
)

SELECT

    B.BOOKING_ID,

    C.CUSTOMER_KEY,

    H.HOTEL_KEY,

    TO_NUMBER(TO_CHAR(B.CHECK_IN_DATE,'YYYYMMDD')) AS DATE_KEY,

    P.PAYMENT_ID,

    B.TOTAL_AMOUNT,

    B.BOOKING_STATUS,

    DATEDIFF(
        DAY,
        B.CHECK_IN_DATE,
        B.CHECK_OUT_DATE
    ) AS STAY_DAYS

FROM SILVER.BOOKING_SILVER B

INNER JOIN GOLD.DIM_CUSTOMER C

ON B.CUSTOMER_ID = C.CUSTOMER_ID

INNER JOIN GOLD.DIM_HOTEL H

ON B.HOTEL_ID = H.HOTEL_ID

LEFT JOIN SILVER.PAYMENT_SILVER P

ON B.BOOKING_ID = P.BOOKING_ID;